Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 40

Layout/LineLength:
  Max: 200

Metrics/AbcSize:
  Enabled: false

